name: Devops Workflow

on:
  push:
    branchs:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de Código
        uses: action/checkout@v4
      
      - name: Mostrar Mensagem
        run: echo "Olá!"